export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const COMPLETE_TODO = 'COMPLETE_TODO'
export const MOVE_UP_TODO = 'MOVE_UP_TODO'
export const MOVE_DOWN_TODO = 'MOVE_DOwN_TODO'
export const EDIT_TODO_ASSIGNEE = 'EDIT_TODO_ASSIGNEE'
